[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./.env" }]

[rpc_endpoints]
baseSepolia = "${RPC_URL}"

[etherscan]
baseSepolia = { key = "${ETHERSCAN_API_KEY}" }
